spring.config.activate.on-profile=prod

spring.application.name=Shine-Public-School-WebApp
#server.servlet.context-path=/shinepublicschool

# =========================
# THYMELEAF
# =========================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# =========================
# DATABASE
# =========================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.validation.mode=none

# =========================
# SQL INIT
# =========================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=false

# =========================
# REST API
# =========================
spring.data.rest.basePath=/data-api

# =========================
# LOGGING
# =========================
logging.level.root=INFO
logging.level.com.shinepublicschool=ERROR
logging.level.com.shinepublicschool.controller=TRACE

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=*

shinepublicschool.contact.pageSize=10