spring.config.activate.on-profile=prod

spring.application.name=Shine-Public-School-WebApp

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.springframework.core.env=DEBUG

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.validation.mode=none

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.flyway.enabled=false

spring.data.rest.basePath=/data-api

logging.level.root=INFO
logging.level.com.shinepublicschool=ERROR
logging.level.com.shinepublicschool.controller=TRACE

management.endpoints.web.exposure.include=*

shinepublicschool.contact.pageSize=10

server.port=${PORT:8080}